name: DevOps Tools Setup

hosts: localhost

become: yes

tasks:
  - name: Update package lists and install basic utilities
    apt:
      update_cache: yes
      name:
        - curl
        - wget
        - unzip
        - tar
        - git
        - jq
        - tree
        - vim
        - nano
        - dnsutils
        - net-tools
        - software-properties-common
        - apt-transport-https
        - ca-certificates
        - gnupg
      state: present

  - name: Install AWS CLI
    unarchive:
      src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      dest: /tmp
      remote_src: yes
    notify: Install AWS CLI

  - name: Install Azure CLI
    shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

  - name: Install Google Cloud SDK
    shell: |
      echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | tee /usr/share/keyrings/cloud.google.gpg
      apt update && apt install -y google-cloud-sdk

  - name: Install Terraform
    shell: |
      curl -fsSL https://apt.releases.hashicorp.com/gpg | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      apt update && apt install -y terraform

  - name: Install kubectl
    get_url:
      url: "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      dest: /usr/local/bin/kubectl
      mode: '0755'

  - name: Install Helm
    shell: |
      curl https://baltocdn.com/helm/signing.asc | apt-key add -
      echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list
      apt update && apt install -y helm

  - name: Install Python and Ansible
    apt:
      name:
        - python3
        - python3-pip
      state: present

  - name: Upgrade pip and install Ansible
    pip:
      name: ansible
      state: latest

  - name: Install GitHub CLI
    shell: |
      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      apt update && apt install -y gh

  - name: Verify installations
    shell: |
      aws --version
      az --version
      gcloud --version
      terraform -v
      kubectl version --client
      helm version
      python3 --version
      ansible --version
      gh --version

handlers:
  - name: Install AWS CLI
    command: sudo /tmp/aws/install
